services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: assesment
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: express_backend
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: assesment
      PORT: 5000
      DB_DIALECT: mysql
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
        
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: nextjs_frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000
    ports:
      - "3000:3000"

volumes:
  mysql-data:
